name: Update Template
on:
  repository_dispatch:
    types: [prod-release]

jobs:
  update:
    name: Update Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.com

      - name: Install dependencies
        run: npm install

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update plugin-sdk version
        run: |
          npm update @dytesdk/plugin-sdk
          git add .
          git commit -m "chore: update plugin-sdk version"
          git push